### ISSUE TITLE
Intranet authentication

### ISSUE THREAD

**Issue by edecadt** [izimio/AGENDA-FLUID-EPITECH-CALENDAR#1]
Does authentication with the intranet still work?
Because it works with Microsoft now

**Comment by izimio** [comment]
As my last knowledge, the script worked successfully last night, so this method worked at least until yesterday ! I'll check it more in the next days

**Comment by edecadt** [comment]
Strange because the Epitech intranet has required authentication with Microsoft for a while.
To tell the truth, I'm looking for a way to authenticate with the intranet API to be able to develop applications but so far I haven't found a very optimal solution because the cookie expires regularly (which is logical) and I cannot reproduce the authentication with Microsoft because there is a double authentication that I cannot automate

**Comment by izimio** [comment]
Epitech has blocked the conventional login method that utilizes individual Epitech accounts. 

A workaround we discovered involves using the parental account. The referent's account possesses equivalent read rights to your own. If you need to modify information, it is advisable to employ Selenium on a server to automatically connect and scrape the JWT.

**Comment by edecadt** [comment]
Okay thank you for your answer.
